appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZlbesqI5k9Lj/OssV4UuuCzw5ipbH66/Q5olErh8c+t13TnWzJwbbqmh5Xu20ruIDJkx4xaCjh0pm1J+FSSPy3Lwez1dMr9TspTmn4HoATAEe7MV/P8LunoakS8PZqfiKbqPNCAG7TSPz+R8AtRu9K/1qcWmmWIE40V2i1xObGMwBD82lTUF4WrxR7MBkLR431CTCGKzd651t31jgkwKtK/dOcLJz/pTq1uJqarUMehCs0s6/7is9XSOLiV7TRgwssXdZFO78uG7KR/19IU/UbdFeqYuRPZiFGBdPP6qhy99qXJrtAMlDRglsk23aK5z8yPzWMlhRnam6LuclgOihZuEQd7U7IPWwLA54ISu0PyiEjk0nArek2aeK8TAtFK/9DcNDTgOrscVZ9NmC5EsI9X+vvTRQzXyaw673wNzfDmiXK0PH6zwdM1qF7FJRAwmsnPnbMBvyshN4jVeS3yVSWJ3oNrd58X7zCUowTTrc9C8kYS8MNJmIxVEoSb0ZM6fTMu5JnqxWktajutaAqD8rqAguQyVeqidp0VBQSl882VIbFmvLSIUz7bk+nigkw+IPWzOyYxKWwCOJu7plEbKgXinyQLIsAI87ulvETTXfKWusBmiThQAAqkst0mGV8/bueQJ9/ncHQWuhoM3k2LdXzrYP20ESMYkEPxg3DzH58g=
